# Generated by Django 3.2 on 2022-03-22 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0002_bookitem_library_rack_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
