# Generated by Django 3.2 on 2022-03-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0004_auto_20220322_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='book_list', to='system_manage.Author'),
        ),
    ]
