# Generated by Django 3.2 on 2022-03-24 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0006_alter_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='subject',
            new_name='category',
        ),
    ]
