# Generated by Django 3.2 on 2022-03-25 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0007_rename_subject_book_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookitem',
            old_name='subject',
            new_name='category',
        ),
    ]
