# Generated by Django 3.2 on 2022-03-25 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0008_rename_subject_bookitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='book_item',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='system_manage.bookitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rack',
            name='location_identifer',
            field=models.CharField(default='23-02-2020', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rack',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
