# Generated by Django 3.2 on 2022-03-25 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0009_auto_20220324_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='book_item',
        ),
        migrations.AddField(
            model_name='bookitem',
            name='rack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system_manage.rack'),
            preserve_default=False,
        ),
    ]
