# Generated by Django 3.2 on 2022-03-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0010_auto_20220324_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='author',
            field=models.ManyToManyField(to='system_manage.Author'),
        ),
    ]
