# Generated by Django 3.2 on 2022-03-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0011_bookitem_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookitem',
            old_name='number_of_pages',
            new_name='cuantity',
        ),
        migrations.RemoveField(
            model_name='bookitem',
            name='added',
        ),
        migrations.RemoveField(
            model_name='bookitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bookitem',
            name='language',
        ),
        migrations.RemoveField(
            model_name='bookitem',
            name='published',
        ),
        migrations.RemoveField(
            model_name='bookitem',
            name='title',
        ),
    ]
