# Generated by Django 3.2 on 2022-03-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0013_bookitem_codig_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='description',
            field=models.CharField(default='lerning', max_length=50),
            preserve_default=False,
        ),
    ]
