# Generated by Django 3.2 on 2022-03-25 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0014_rack_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitem',
            name='author',
        ),
    ]
