# Generated by Django 3.2 on 2022-03-26 01:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_manage', '0015_remove_bookitem_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
