# Generated by Django 3.2 on 2022-03-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0017_alter_bookitem_rent_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
