# Generated by Django 3.2 on 2022-03-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_is_staff_user_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_membership',
            field=models.DateField(default='2020-12-15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='total_books_checkedout',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
