# Generated by Django 3.2 on 2022-03-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220325_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_membership',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_books_checkedout',
            field=models.IntegerField(default=0),
        ),
    ]
